const employees = [
  {
    id: 1,
    name: "Aarav Sharma",
    email: "employee1@example.com",
    password: "123",
    taskCounts: {
      active: 0,
      newTask: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        id: "cb7ca1eb-39f0-43de-8f9d-a109e884c766",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Update Website",
        taskDescription: "Revamp the homepage design",
        taskDate: "2024-10-12",
        category: "Design",
      },
      {
        id: "029cee22-25a6-448f-88b0-1023ee51fb6a",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Prepare Banner",
        taskDescription: "Design homepage banner",
        taskDate: "2024-10-13",
        category: "Design",
      },
      {
        id: "289ce3ff-0d65-41d7-b31c-85303f2edc05",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Client Meeting",
        taskDescription: "Discuss project requirements",
        taskDate: "2024-10-10",
        category: "Meeting",
      },
    ],
  },

  {
    id: 2,
    name: "Priya Verma",
    email: "employee2@example.com",
    password: "123",
    taskCounts: {
      active: 0,
      newTask: 1,
      completed: 2,
      failed: 0,
    },
    tasks: [
      {
        id: "cef51041-3664-4cb9-9d32-18542eab268f",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Create Dashboard",
        taskDescription: "Develop admin dashboard UI",
        taskDate: "2024-10-13",
        category: "Development",
      },
      {
        id: "ce2cc4df-5fdb-4971-9264-978854795f35",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Database Backup",
        taskDescription: "Backup production database",
        taskDate: "2024-10-09",
        category: "Database",
      },
      {
        id: "774cae50-9816-4768-b5ef-4c1b6f5b5ee9",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Deploy API",
        taskDescription: "Deploy REST API to server",
        taskDate: "2024-10-11",
        category: "Deployment",
      },
    ],
  },

  {
    id: 3,
    name: "Rohan Gupta",
    email: "employee3@example.com",
    password: "123",
    taskCounts: {
      active: 0,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        id: "3767ad5d-4364-4333-86a4-d336a3193199",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Write Documentation",
        taskDescription: "Prepare API documentation",
        taskDate: "2024-10-14",
        category: "Documentation",
      },
      {
        id: "10dcca87-b4d5-49cb-bd04-859ef75509a2",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Code Review",
        taskDescription: "Review teammate's pull request",
        taskDate: "2024-10-09",
        category: "Development",
      },
      {
        id: "799ffdbc-ddb2-45a8-8632-0c492af02c5a",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Optimize Queries",
        taskDescription: "Improve SQL query performance",
        taskDate: "2024-10-07",
        category: "Database",
      },
    ],
  },

  {
    id: 4,
    name: "Sneha Kapoor",
    email: "employee4@example.com",
    password: "123",
    taskCounts: {
      active: 0,
      newTask: 0,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        id: "0ea015c8-d69b-463e-9c08-fbd2f0e1470a",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Design Logo",
        taskDescription: "Create branding assets",
        taskDate: "2024-10-15",
        category: "Design",
      },
      {
        id: "ec55cc4f-b206-4afa-826c-f27950590061",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Security Audit",
        taskDescription: "Check application vulnerabilities",
        taskDate: "2024-10-06",
        category: "Security",
      },
      {
        id: "8d800d3f-0437-4a3a-b8aa-9d3e60bc32cb",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Fix CSS Issues",
        taskDescription: "Resolve responsive layout bugs",
        taskDate: "2024-10-10",
        category: "Frontend",
      },
    ],
  },

  {
    id: 5,
    name: "Karan Mehta",
    email: "employee5@example.com",
    password: "123",
    taskCounts: {
      active: 0,
      newTask: 3,
      completed: 0,
      failed: 0,
    },
    tasks: [
      {
        id: "02eeb0f1-b2c4-438f-a780-bcbe001529a9",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Prepare Presentation",
        taskDescription: "Create slides for client demo",
        taskDate: "2024-10-16",
        category: "Presentation",
      },
      {
        id: "8aba5328-6ce9-4eb4-979e-0ab936de371c",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Send Invoice",
        taskDescription: "Email invoice to client",
        taskDate: "2024-10-17",
        category: "Finance",
      },
      {
        id: "c29a92a9-1ca5-4291-8cc1-fabb57aace5d",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Test Mobile App",
        taskDescription: "Perform regression testing",
        taskDate: "2024-10-18",
        category: "Testing",
      },
    ],
  },
];
const admin = [
  {
    id: 0,
    name: "Admin User",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage=()=>{
    if(!localStorage.getItem('employees')){
    localStorage.setItem('employees',JSON.stringify(employees))
    localStorage.setItem('admin',JSON.stringify(admin))
    }
}
export const getLocalStorage=()=>{
    let employees=JSON.parse(localStorage.getItem('employees'))
    let admin=JSON.parse(localStorage.getItem('admin'))
    return {employees,admin}
}